name = "your-worker-name"
type = "javascript"  # Make sure this is set correctly

[env.production]
GITHUB_REPO = "username/repository"
GITHUB_TOKEN = "your-github-token"
GITHUB_BRANCH = "main"  # Optional, set default branch
